### ISSUE TITLE
Metadata (and queryString?) should use an Array Type instead of Tuple Type

### ISSUE THREAD

**Issue by XavierGeerinck** [dapr/python-sdk#328]
When working with metadata, the examples show a Tuple is required (as is the Type). However, when using the `for key, value in metadata` an array of tuples is required.

## Code reference:

https://github.com/dapr/python-sdk/blob/bba469a2ee46c38b6ab523bd3b575c9407438937/dapr/clients/http/dapr_invocation_http_client.py#L72

## Broken Example:

```python
res = d.invoke_method(
    app_id="my-app",
    method_name="process/binary",
    data=data,
    content_type="application/octet-stream",
    http_verb="POST",
    metadata=(
        ("hello", "world")
    )
)
```

This will throw:

```
== APP ==   File "/home/MASKED/.pyenv/versions/3.8.10/lib/python3.8/site-packages/dapr/clients/http/dapr_invocation_http_client.py", line 64, in invoke_method
== APP ==     for key, value in metadata:
== APP == ValueError: too many values to unpack (expected 2)
```

## Working Example:

```python
res = d.invoke_method(
    app_id="my-app",
    method_name="process/binary",
    data=data,
    content_type="application/octet-stream",
    http_verb="POST",
    metadata=[
        ("hello", "world")
    ]
)
```

**Comment by wcs1only** [comment]
In python you need to specify a tuple of tuples like this:
```python
metadata=(
    ("hello", "world), 
)
```

The reason being that `(expression)` gets reduced to `expression` before anything else so (("hello", "world")) is reduced to ("hello", "world") which is a tuple of strings instead of a tuple of tuples. 

Which example where you reading when you found this? I suspect this is just a typo in the documentation.
