### ISSUE TITLE
HTTP: Input Binding Support

### ISSUE THREAD

**Issue by XavierGeerinck** [dapr/python-sdk#342]
Bindings should be supported on the HTTP Protocol, currently it seems that the FastAPI implementation does not have it? @wcs1only ?

**Comment by artursouza** [comment]
My understanding is that binding does not require the SDK for any functionality. We would just need an example for HTTP input binding - which does not even need the SDK to work, actually.

**Comment by XavierGeerinck** [comment]
Reiterating the discussion maybe from yesterday (maybe we should have more opinions on this - @paulyuk ?) but in my opinion you should be able to interact with Dapr through the SDK for ANYTHING you want. Which also means Bindings.

If bindings are not supported, I wouldn't go that far as to say that: "it does not require the SDK For any functionality".

Personally again, It's not because we support HTTP that we should rely on people using HTTP and implementing a web server :) but just my 2 cents. Just imagine that you are writing a simple processor. Do you want to go ahead and set up an entire web server for this? Or do you expect the SDK to do just that?

Another example I was thinking of: let's imagine you are doing the same through the Redis SDK. There we also don't have to setup a web server right :) if Dapr abstracts everything away, the SDKs should as well I think.

**Comment by berndverst** [comment]
If you want a mechanism that is handled / managed by Dapr than that is gRPC in my opinion.

As a Flask or Fast API user I don't find Dapr registering routes without my knowledge to be reassuring.

Consider this:
By default the sidecar sends events for input bindings to `POST /bindingname`. But this is configurable to be any route you want (via the component metadata).

So naturally one must manually edit edit their code.

Here is native Flask code:
```python
@app.route('/myinputbinding', method='POST')
def myinputhandler():
  request_body = request.json()
  # do stuff
```

So you are proposing that we have what?

```python
@daprapp.binding('myinputbinding')
def myinputhandler(body):
  # do stuff
```

The problem with this approach of course is that that I can set up a custom route that is different from the binding name. Also, this decorator would have to handle setting up the flask route under the hood.

The same generally applies to Fast API by the way. I am using Flask for the discussion because it's more popular and common.

If you want to use HTTP there is no way around using and implementing a web server - surely Dapr shouldn't fully be managing a web server for you (which Flask and Fast API extensions are).

I don't understand the Redis SDK comparison - doesn't that open a connection on a binary wire protocol and then stream data? That doesn't seem to apply here, but even so gRPC is much closer to that approach than HTTP.

**Comment by berndverst** [comment]
So this just standard Fast API / Flask stuff.

```python

from fastapi import Request

@app.post("/myinputbinding")
async def handlebinding(request: Request):
  # do stuff
```

**Comment by XavierGeerinck** [comment]
Hi @berndverst ! Thanks a lot for clarifying your thoughts. 

Adding on this, the use case scenario I typically take here is if we are developing a microservice that wants to just do one thing: "Process Orders".

Would a user then need to implement a full web server to accomplish this scenario? 

As normally, when I am a user that wants to create this, I would follow these steps?
1. Install Pub Sub (e.g. Redis)
2. Use the Pub Sub Library and import it
3. Listen to changes

No Web Server will be imported in these steps, thus posing the question why we don't ship a standard Web Server as a lower boundary?

Yes, I agree you should be able to hook it up to an existing HTTP Server, but I think we should also offer a standard one.

**Comment by berndverst** [comment]
The recommendation is to use gRPC or set up your own Flask, Fast API server etc
