### ISSUE TITLE
Unable to specify response body and 500 status code for python gRPC service

### ISSUE THREAD

**Issue by timgabrhel** [dapr/python-sdk#465]
## In what area(s)?

/area runtime

## What version of Dapr?

python dapr-ext-grpc 1.7

## Expected Behavior

When an exception occurs in my code grpc service, I want the result to be an HTTP 500 exception with the json message box

## Actual Behavior

If I set the content type to `text/plain`, then the error message is returned, but the HTTP status code is 200
If I set the content type to `application/json`, the error message is lost and the error is a dapr exception of 

## Steps to Reproduce the Problem

```py
from dapr.ext.grpc import App, InvokeMethodRequest, InvokeMethodResponse

app = App()

@app.method(name='Test')
def test(request: InvokeMethodRequest) -> InvokeMethodResponse:

    try:
        return InvokeMethodResponse(custom_object, content_type="application/json") # works

    except Exception as e:        
        error_message = getattr(e, 'message', repr(e))

        # results in a 500 but it appears to be the gRPC > HTTP translation.
        #return InvokeMethodResponse({"error":error_message}, content_type="application/json", headers=[("dapr-grpc-status-code", 
"500")])

        # results in a 200 but I see the proper response body
        #return InvokeMethodResponse(json.dumps({"error":error_message}), content_type="text/plain", headers=[("dapr-grpc-status-code", "500")])

app.run(50022)
```

When returning the 500 from the exception block, I see this HTTP response on my client.
```json
{
  "code": 2,
  "message": "Exception calling application: invalid data type <class 'dict'>"
}
```

**Comment by berndverst** [comment]
What are you actually invoking @timgabrhel ? This sound to me that the server is returning a successful gRPC response whose content is actually an error. The `dapr-` headers indicate that these are headers from the response the Dapr sidecar got calling the remote service.

This is actually how Dapr Service Invocation works since the request to the Dapr Sidecar succeeded, but the Dapr sidecar got an error calling the destination service.

I would investigate the recipient service you are trying to invoke for errors.

Given the way the Dapr runtime works, to me this sounds like `dapr.ext.grpc` is working as intended.

**Comment by timgabrhel** [comment]
@berndverst You are spot on. Unfortunately it was a local error due to a null value coming in mistakenly on the request object, so the error message now makes sense, though it wasn't obvious until I could locate a full stack trace from AKS.
