### ISSUE TITLE
Support DAPR_HTTP_ENDPOINT and/or DAPR_GRPC_ENDPOINT

### ISSUE THREAD

**Issue by artursouza** [dapr/python-sdk#577]
## Describe the proposal

Allow consistent way to configure endpoint for Dapr's sidecar, while enabling remote sidecar configuration.

Child of https://github.com/dapr/dapr/issues/6035

SDK should parse these in a consistent way, so operators have a consistent environment variable to set for Dapr apps. Right now, each SDK has their own way of configuring the endpoint for Dapr's sidecar.

If SDK allows gRPC communication from SDK to sidecar, then `DAPR_GRPC_ENDPOINT` must be supported.
If SDK allows HTTP communication from SDK to sidecar, then `DAPR_HTTP_ENDPOINT` must be supported.
DAPR_HTTP_ENDPOINT and DAPR_GRPC_ENDPOINT and not exclusive, meaning it is acceptable to support both, like in the Java SDK, if the SDK supports both protocols.
Also, companies might decide to offer different endpoints per protocol, so there is not an unique environment variable for both.

**Comment by berndverst** [comment]
@artursouza in Python this has been supported for a very long time using the environment variable `DAPR_RUNTIME_HOST`. This predates my time as maintainer.

**Comment by berndverst** [comment]
If `DAPR_GRPC_ENDPOINT` and `DAPR_HTTP_ENDPOINT` must be supported, then what is necessary is the following:

Add these to the config options - but do not provide defaults (use `None`). Instead we should fall back to `DAPR_RUNTIME_HOST` for backwards compatibility.
https://github.com/dapr/python-sdk/blob/master/dapr/conf/global_settings.py

In the `grpc` client code, we should use the config value `DAPR_GRPC_ENDPOINT` `if not None`, otherwise fall back to `DAPR_RUNTIME_HOST`.

https://github.com/dapr/python-sdk/blob/5051a9d5d92003924322a8ddbdf230fb8a872dd7/dapr/clients/grpc/client.py#L125-L126

https://github.com/dapr/python-sdk/blob/5051a9d5d92003924322a8ddbdf230fb8a872dd7/dapr/aio/clients/grpc/client.py#L126-L127

In the `http` client code, we should use the config value `DAPR_HTTP_ENDPOINT` `if not None`, otherwise fall back to `DAPR_RUNTIME_HOST`

https://github.com/dapr/python-sdk/blob/5051a9d5d92003924322a8ddbdf230fb8a872dd7/dapr/clients/http/client.py#L53

**Comment by berndverst** [comment]
Something like

```python3
 if not address: 
     address = f"{settings.DAPR_GRPC_ENDPOINT if settings.DAPR_GRPC_ENDPOINT else settings.DAPR_RUNTIME_HOST}:{settings.DAPR_GRPC_PORT}" 
```

**Comment by artursouza** [comment]
These environment variables will bring two things:
1. Allow users to configure remote endpoints with a single value instead of HOST and PORT.
2. Have consistency across SDKs since devops can configure this in a single value (per protocol) instead of having devops  to know which language each app container is using.

**Comment by artursouza** [comment]
At this stage, only http and https protocols are needed.
