### ISSUE TITLE
Response body is lost when using dapr client

### ISSUE THREAD

**Issue by leonidgil** [dapr/python-sdk#614]
When using dapr client to send an http request. If the server returns a response with a status code which is in a range outside of 200-300 and the response contains a body describing error details, the response content may still be discarded

The function convert_to_error() of class DaprHttpClient assumes that the error response contains keys “message” and “errorCode” in desterilized error_info.

In our case, for example, the error response looks like this
{'requestId': 1, 'status': 'Failed', 'statusDescription': ‘error reason is here’}

DaprInternalError which is raised in this case looks like this:
dapr.clients.exceptions.DaprInternalError: (None, 'UNKNOWN')

And we lost the useful information about error reason.

Suggestion: when wrapping error response into DaprInternalError always include response body into exception

**Comment by berndverst** [comment]
We generally recommend performing service invocation directly via HTTP libraries (like `requests`) instead at this time, rather than using the Dapr SDK. Our documentation on docs.dapr.io has been updated accordingly.

I opened a PR to add `raw_response_bytes` to the `DaprInteralError` class, so that you can get the complete response the way it is being received.

**Comment by berndverst** [comment]
Fixed in 1.12.0
