### ISSUE TITLE
[Proposal] Using Dapr and Python-sdk for ML/DL model deployment

### ISSUE THREAD

**Issue by youngbupark** [dapr/python-sdk#68]
## Describe the proposal

The ultimate goal of ML and DL model development is to integrate with the production services. Typically, ML and DL engineers focus on model development rather than how they will integrate model with their services. 

Many articles and tutorials introduces how to serve the model with Flask. Once they have Flask service with their model to their production, the backend and frontend services need to implement client code to talk to model server. 

Dapr and Python-sdk will be able to resolve this problem easier. So ML engineer creates micro service and deploy it to production cluster without the knowledge of http restful api server and microservice deployment. Backend engineer can use service invocation api to use the model without model server client implementation.

**Comment by chinzhiweiblank** [comment]
I would suggest porting over from Flask to [FastApi](https://fastapi.tiangolo.com/alternatives/#flask). FastApi and Flask are similar in style but FastApi has more benefits than Flask, particularly its Async [requests](https://towardsdatascience.com/why-we-switched-from-flask-to-fastapi-for-production-machine-learning-765aab9b3679).

**Comment by youngbupark** [comment]
> I would suggest porting over from Flask to [FastApi](https://fastapi.tiangolo.com/alternatives/#flask). FastApi and Flask are similar in style but FastApi has more benefits than Flask, particularly its Async [requests](https://towardsdatascience.com/why-we-switched-from-flask-to-fastapi-for-production-machine-learning-765aab9b3679).

Thanks for the information. Flask is used for Actor Service, not for all Dapr API Appcallback.

Dapr Appcallback in python sdk will use gRPC - https://github.com/dapr/python-sdk/issues/65

**Comment by XavierGeerinck** [comment]
Awesome idea! This is something I have encountered a lot when working with customers... data scientists are very good in creating models, but most often come from a different background and have difficulties integrating with an application.

The main question I had when reading this: how far does Dapr want to go in ML Model support compared to existing tools out there? Depending on this question it might be interesting to branch of a new repo such as `python-ml-sdk` under Dapr I think...

Otherwise, while brainstorming about this I was thinking about this:
* Do you have an interface in mind?
  * The Azure ML Services team did a lot of work already in creating an interface for packaging models and deploying them to ACI easily (https://docs.microsoft.com/en-us/azure/machine-learning/how-to-deploy-and-where) + AutoML creates a model automatically and uses this as well. Might be interesting to sync with them on this compatibility/business wise :) 
* Would you support the following in this proposal?
  * Model versioning?
  * A/B Testing of models? 
* Points that might be interesting in the Dapr ecosystem depending on how far you want to go
  * Data integration and pipelining
  * Training scale-out integration

Looking forward to your thoughts!
