### ISSUE TITLE
Issues templates don't offer a general template

### ISSUE THREAD

**Issue by cicoyle** [dapr/python-sdk#734]
## Expected Behavior

I would expect to open a general issue/feature request unrelated to workflows for this sdk. Upon looking at the templates for this sdk I see:
![image](https://github.com/user-attachments/assets/34ca4f68-2d37-4aae-b406-b2b042767b28)

There is no general issue template available to developers to use. I think the template descriptions should be generalized to be more broad, beyond `workflows vs not workflows`

## Steps to Reproduce the Problem

Open an issue in this sdk.

**Comment by berndverst** [comment]
This is on purpose because people would constantly mis-categorize things.

**Comment by berndverst** [comment]
Keep in mind that we have 5 SDKs published via this repo:

`dapr`
`dapr-ext-grpc`
`dapr-ext-fastapi`
`flask-dapr`
`dapr-ext-workflow`

The latter is the most different and has in essence different maintainers (because most of the work is actually in `durable-task-python` which is a different repo entirely)

That is why issue templates are separated into:
Bug / Feature Request / Question -- Workflow SDK
Bug / Feature Request / Question -- Everythin Else
